version: "1"
services:
  app:
    image: "jsb13207/my-golang-app:latest"
    ports:
      - "8080:80"
    volumes:
      - "./src:/go/src/"
    working_dir: /go/src/${PROJECT_NAME}/
    command: go run hello-world.go
